### PR TITLE
[#99347680] Vimeo sync appears to occasionally cause a race condition which blocks requests until the sync has finished.

### PR DESCRIPTION
**Pull request by Ignigena**
- Refactors Vimeo sync function to utilize Promises
- Cron job now boots an on-demand Heroku dyno to perform sync

### CODE REVIEW

**Comment by Ignigena** [comment]
I rebased this against master so we can perhaps deploy this before the UI work is finished.

Tests are failing, and the additional work I did is not test covered. Let me know if we should get tests passing and written for this component before we deploy the fix.

**Comment by Josh-Mosh** [comment]
This seems like a big enough issue that we can push out now and get tests passing after the fact.  I'm assuming this doesn't break actual login functionality as the failing test would imply?  It's the test that's broken, not the actual login functionality?  If that's the case, I'm good to merge if you say it's all good.

**Comment by Ignigena** [comment]
I've deployed to staging and made some minor tweaks based on bugs that were identified. Everything appears to be working with the new worker script running on it's own machine. Added an additional Service which will allow us to create worker machines in a standardized way.

Here are log snippets from Staging demonstrating the Vimeo machine lifecycle:

```
2015-08-02T14:23:02.048106+00:00 heroku[run.1596]: Starting process with command `./workers/vimeoSync.js`
2015-08-02T14:23:02.670477+00:00 heroku[run.1596]: State changed from starting to up
2015-08-02T14:23:07.519970+00:00 app[run.1596]: 53590f3b33e3170800b56c85: Querying Vimeo API.
2015-08-02T14:23:07.555191+00:00 app[run.1596]: 53225a780c47fa1100b5ca3a: Querying Vimeo API.
2015-08-02T14:23:07.459035+00:00 app[run.1596]: Syncing Vimeo storage...
2015-08-02T14:23:07.551966+00:00 app[run.1596]: 53a769bbb4bbcf10004de291: Querying Vimeo API.
2015-08-02T14:23:08.838309+00:00 app[run.1596]: 53a769bbb4bbcf10004de291: Page 1 - found 0 matching videos.
2015-08-02T14:23:08.837905+00:00 app[run.1596]: 53a769bbb4bbcf10004de291: Found 7 total pages of videos.
2015-08-02T14:23:08.876323+00:00 app[run.1596]: 53590f3b33e3170800b56c85: Found 2 total pages of videos.
2015-08-02T14:23:09.003359+00:00 app[run.1596]: 53225a780c47fa1100b5ca3a: Found 17 total pages of videos.
2015-08-02T14:23:08.911423+00:00 app[run.1596]: 53590f3b33e3170800b56c85: Page 1 - found 26 matching videos.
2015-08-02T14:23:09.013878+00:00 app[run.1596]: 53225a780c47fa1100b5ca3a: Page 1 - found 10 matching videos.
2015-08-02T14:23:10.181224+00:00 app[run.1596]: 53a769bbb4bbcf10004de291: Page 1 - found 0 matching videos.
2015-08-02T14:23:11.202731+00:00 app[run.1596]: 53a769bbb4bbcf10004de291: Page 3 - found 0 matching videos.
2015-08-02T14:23:11.426547+00:00 app[run.1596]: 53a769bbb4bbcf10004de291: Page 5 - found 0 matching videos.
2015-08-02T14:23:11.408994+00:00 app[run.1596]: 53a769bbb4bbcf10004de291: Page 2 - found 0 matching videos.
2015-08-02T14:23:11.544663+00:00 app[run.1596]: 53a769bbb4bbcf10004de291: Page 4 - found 0 matching videos.
2015-08-02T14:23:12.476029+00:00 app[run.1596]: 53590f3b33e3170800b56c85: Page 1 - found 26 matching videos.
2015-08-02T14:23:12.884722+00:00 app[run.1596]: 53225a780c47fa1100b5ca3a: Page 1 - found 10 matching videos.
2015-08-02T14:23:13.114078+00:00 app[run.1596]: 53225a780c47fa1100b5ca3a: Page 3 - found 6 matching videos.
2015-08-02T14:23:12.974011+00:00 app[run.1596]: 53225a780c47fa1100b5ca3a: Page 2 - found 8 matching videos.
2015-08-02T14:23:13.196418+00:00 app[run.1596]: 53a769bbb4bbcf10004de291: Page 6 - found 0 matching videos.
2015-08-02T14:23:13.860817+00:00 app[run.1596]: 53225a780c47fa1100b5ca3a: Page 4 - found 11 matching videos.
2015-08-02T14:23:14.127899+00:00 app[run.1596]: 53225a780c47fa1100b5ca3a: Page 6 - found 13 matching videos.
2015-08-02T14:23:14.345979+00:00 app[run.1596]: 53225a780c47fa1100b5ca3a: Page 7 - found 12 matching videos.
2015-08-02T14:23:14.399328+00:00 app[run.1596]: 53225a780c47fa1100b5ca3a: Page 5 - found 11 matching videos.
2015-08-02T14:23:15.411340+00:00 app[run.1596]: 53225a780c47fa1100b5ca3a: Page 9 - found 6 matching videos.
2015-08-02T14:23:15.530126+00:00 app[run.1596]: 53225a780c47fa1100b5ca3a: Page 8 - found 10 matching videos.
2015-08-02T14:23:15.870432+00:00 app[run.1596]: 53225a780c47fa1100b5ca3a: Page 10 - found 9 matching videos.
2015-08-02T14:23:16.130528+00:00 app[run.1596]: 53225a780c47fa1100b5ca3a: Page 11 - found 6 matching videos.
2015-08-02T14:23:16.224287+00:00 app[run.1596]: 53225a780c47fa1100b5ca3a: Page 12 - found 0 matching videos.
2015-08-02T14:23:17.352692+00:00 app[run.1596]: 53225a780c47fa1100b5ca3a: Page 14 - found 1 matching videos.
2015-08-02T14:23:17.672348+00:00 app[run.1596]: 53225a780c47fa1100b5ca3a: Page 13 - found 1 matching videos.
2015-08-02T14:23:17.904012+00:00 app[run.1596]: 53225a780c47fa1100b5ca3a: Page 16 - found 8 matching videos.
2015-08-02T14:23:18.307816+00:00 app[run.1596]: 53225a780c47fa1100b5ca3a: Page 15 - found 4 matching videos.
2015-08-02T14:23:18.313148+00:00 app[run.1596]: Vimeo sync completed in 10855ms.
2015-08-02T14:23:19.101113+00:00 heroku[run.1596]: Process exited with status 0
2015-08-02T14:23:19.112666+00:00 heroku[run.1596]: State changed from up to complete
```

**Comment by Ignigena** [comment]
All tests are passing. Ready to merge on your command.

I've enabled automatic deployment on master when CI passes. So merging will cause a deploy as well.

**Pull request merged**
